openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Metrics API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: Metrics
paths:
  /api/{env}/metrics/cluster:
    get:
      description: show cluster overview
      tags:
      - Metrics
      summary: Apache Dubbo Show Cluster Overview
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.ClusterMetricsRes'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvMetricsCluster
      x-operation-id-source: derived
  /api/{env}/metrics/flow:
    get:
      description: show Prometheus collected metrics
      tags:
      - Metrics
      summary: Apache Dubbo Show Prometheus Collected Metrics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.FlowMetricsRes'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvMetricsFlow
      x-operation-id-source: derived
  /api/{env}/metrics/metadata:
    get:
      description: show metadata of the cluster, like dubbo versions, protocols, etc.
      tags:
      - Metrics
      summary: Apache Dubbo Show Metadata of the Cluster, Like Dubbo Versions, Protocols, Etc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.Metadata'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvMetricsMetadata
      x-operation-id-source: derived
  /api/{env}/version:
    get:
      description: show basic information of the Admin process
      tags:
      - Metrics
      summary: Apache Dubbo Show Basic Information of the Admin Process
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/version.Version'
      operationId: getApiByEnvVersion
      x-operation-id-source: derived
components:
  schemas:
    model.Metadata:
      type: object
      properties:
        configCenter:
          type: string
        metadataCenter:
          type: string
        protocols:
          type: array
          items: {}
        registry:
          type: string
        rules:
          type: array
          items:
            type: string
        versions:
          type: array
          items: {}
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
    version.Version:
      type: object
      properties:
        buildDate:
          type: string
        compiler:
          type: string
        gitCommit:
          type: string
        gitTreeState:
          type: string
        gitVersion:
          type: string
        goVersion:
          type: string
        platform:
          type: string
    model.ClusterMetricsRes:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: integer
    model.FlowMetricsRes:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: number
