swagger: '2.0'
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin ConditionRule TagRule API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
host: 127.0.0.1:38080
basePath: /
tags:
- name: TagRule
paths:
  /api/{env}/rules/route/tag:
    get:
      description: Search rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Search Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: application and service must not left empty at the same time
        name: application
        in: query
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/model.TagRouteDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    post:
      description: Create a new tag rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Create a New Tag Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - description: rule input
        name: tagRoute
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.TagRouteDto'
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/rules/route/tag/disable/{id}:
    put:
      description: Disable the specified rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Disable the Specified Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: rule id
        name: id
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/rules/route/tag/enable/{id}:
    put:
      description: Enable the specified rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Enable the Specified Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: rule id
        name: id
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/rules/route/tag/{id}:
    get:
      description: Show the detail of one specified rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Show the Detail of One Specified Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: rule id
        name: id
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/model.TagRouteDto'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    post:
      description: Update rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Update Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: rule id
        name: id
        in: path
        required: true
      - description: rule input
        name: tagRoute
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.TagRouteDto'
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    delete:
      description: Delete the specified rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TagRule
      summary: Apache Dubbo Delete the Specified Rule
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: rule id
        name: id
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
definitions:
  model.TagRouteDto:
    type: object
    required:
    - configVersion
    - enabled
    - tags
    properties:
      application:
        type: string
      configVersion:
        type: string
      enabled:
        type: boolean
      force:
        type: boolean
      id:
        type: string
      priority:
        type: integer
      runtime:
        type: boolean
      service:
        type: string
      serviceGroup:
        type: string
      serviceVersion:
        type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/model.Tag'
  model.StringMatch:
    type: object
    properties:
      empty:
        type: string
      exact:
        type: string
      noempty:
        type: string
      prefix:
        type: string
      regex:
        type: string
      wildcard:
        type: string
  model.Tag:
    type: object
    required:
    - match
    - name
    properties:
      addresses:
        type: array
        items:
          type: string
      match:
        type: array
        items:
          $ref: '#/definitions/model.ParamMatch'
      name:
        type: string
  model.ParamMatch:
    type: object
    properties:
      key:
        type: string
      value:
        $ref: '#/definitions/model.StringMatch'
  model.HTTPError:
    type: object
    properties:
      error:
        description: error message
        type: string
