swagger: '2.0'
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin ConditionRule Services API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
host: 127.0.0.1:38080
basePath: /
tags:
- name: Services
paths:
  /api/{env}/applications:
    get:
      description: Get all applications
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Services
      summary: Apache Dubbo Get All Applications
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/consumers:
    get:
      description: Get all consumers
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Services
      summary: Apache Dubbo Get All Consumers
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/service:
    get:
      description: Search services by different patterns and keywords
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Services
      summary: Apache Dubbo Search Services by Different Patterns and Keywords
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: 'supported values: application, service or ip'
        name: pattern
        in: query
        required: true
      - type: string
        description: keyword to search
        name: filter
        in: query
        required: true
      - type: string
        description: page number
        name: page
        in: query
      - type: string
        description: page size
        name: size
        in: query
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/model.ListServiceByPage'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/service/{service}:
    get:
      description: Show detail of the specified service
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Services
      summary: Apache Dubbo Show Detail of the Specified Service
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      - type: string
        description: 'service format: ''group/service:version'''
        name: service
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/model.ServiceDetailDTO'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
  /api/{env}/services:
    get:
      description: Get all services
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Services
      summary: Apache Dubbo Get All Services
      parameters:
      - type: string
        default: dev
        description: environment
        name: env
        in: path
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
definitions:
  model.ServiceDTO:
    type: object
    properties:
      appName:
        type: string
      group:
        type: string
      registrySource:
        $ref: '#/definitions/model.RegistrySource'
      service:
        type: string
      version:
        type: string
  time.Duration:
    type: integer
    enum:
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    x-enum-varnames:
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
  model.RegistrySource:
    type: string
    enum:
    - ALL
    x-enum-varnames:
    - All
  model.ListServiceByPage:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/model.ServiceDTO'
      first:
        type: boolean
      last:
        type: boolean
      offset:
        type: integer
      pageNumber:
        type: string
      size:
        type: string
      totalElements:
        type: integer
      totalPages:
        type: integer
  model.Provider:
    type: object
    properties:
      address:
        type: string
      alived:
        type: integer
      application:
        type: string
      created:
        type: string
      dynamic:
        type: boolean
      enabled:
        type: boolean
      expired:
        $ref: '#/definitions/time.Duration'
      hash:
        type: string
      id:
        type: integer
      ids:
        type: array
        items:
          type: integer
      miss:
        type: boolean
      modified:
        type: string
      now:
        type: string
      operator:
        type: string
      operatorAddress:
        type: string
      parameters:
        type: string
      registry:
        type: string
      registrySource:
        $ref: '#/definitions/model.RegistrySource'
      serialization:
        type: string
      service:
        type: string
      timeout:
        type: integer
      url:
        type: string
      username:
        type: string
      weight:
        type: integer
  model.ServiceDetailDTO:
    type: object
    properties:
      application:
        type: string
      consumers:
        type: array
        items:
          $ref: '#/definitions/model.Consumer'
      metadata: {}
      providers:
        type: array
        items:
          $ref: '#/definitions/model.Provider'
      service:
        type: string
  model.HTTPError:
    type: object
    properties:
      error:
        description: error message
        type: string
  model.Consumer:
    type: object
    properties:
      address:
        type: string
      alived:
        type: integer
      application:
        type: string
      collected:
        $ref: '#/definitions/time.Duration'
      created:
        type: string
      expired:
        $ref: '#/definitions/time.Duration'
      hash:
        type: string
      id:
        type: integer
      ids:
        type: array
        items:
          type: integer
      miss:
        type: boolean
      modified:
        type: string
      now:
        type: string
      operator:
        type: string
      operatorAddress:
        type: string
      parameters:
        type: string
      registry:
        type: string
      result:
        type: string
      service:
        type: string
      statistics:
        type: string
      username:
        type: string
