swagger: '2.0'
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin ConditionRule TrafficRetry API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
host: 127.0.0.1:38080
basePath: /
tags:
- name: TrafficRetry
paths:
  /api/{env}/traffic/retry:
    get:
      description: get rule list
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficRetry
      summary: Apache Dubbo Get Rule List
      parameters:
      - type: string
        description: service name
        name: service
        in: query
        required: true
      - type: string
        description: service version
        name: version
        in: query
        required: true
      - type: string
        description: service group
        name: group
        in: query
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/model.Retry'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    put:
      description: update rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficRetry
      summary: Apache Dubbo Update Rule
      parameters:
      - description: rule
        name: retry
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.Retry'
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    post:
      description: create rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficRetry
      summary: Apache Dubbo Create Rule
      parameters:
      - description: rule
        name: retry
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.Retry'
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    delete:
      description: delete rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficRetry
      summary: Apache Dubbo Delete Rule
      parameters:
      - type: string
        description: service name
        name: service
        in: query
        required: true
      - type: string
        description: service version
        name: version
        in: query
        required: true
      - type: string
        description: service group
        name: group
        in: query
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
definitions:
  model.Retry:
    type: object
    required:
    - retry
    - service
    properties:
      group:
        type: string
      retry:
        type: integer
      service:
        type: string
      version:
        type: string
  model.HTTPError:
    type: object
    properties:
      error:
        description: error message
        type: string
