openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Traffic Weight API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: TrafficWeight
paths:
  /api/{env}/traffic/weight:
    get:
      description: get rule list
      tags:
      - TrafficWeight
      summary: Apache Dubbo Get Rule List
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.Weight'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvTrafficWeight
      x-operation-id-source: derived
    put:
      description: update rule
      tags:
      - TrafficWeight
      summary: Apache Dubbo Update Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Weight'
        description: rule
        required: true
      operationId: putApiByEnvTrafficWeight
      x-operation-id-source: derived
    post:
      description: create rule
      tags:
      - TrafficWeight
      summary: Apache Dubbo Create Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Weight'
        description: rule
        required: true
      operationId: postApiByEnvTrafficWeight
      x-operation-id-source: derived
    delete:
      description: delete rule
      tags:
      - TrafficWeight
      summary: Apache Dubbo Delete Rule
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: deleteApiByEnvTrafficWeight
      x-operation-id-source: derived
components:
  schemas:
    model.Weight:
      type: object
      required:
      - match
      - weight
      properties:
        match:
          $ref: '#/components/schemas/model.ConditionMatch'
        weight:
          type: integer
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
    model.AddressMatch:
      type: object
      properties:
        cird:
          type: string
        exact:
          type: string
        wildcard:
          type: string
    model.StringMatch:
      type: object
      properties:
        empty:
          type: string
        exact:
          type: string
        noempty:
          type: string
        prefix:
          type: string
        regex:
          type: string
        wildcard:
          type: string
    model.ListStringMatch:
      type: object
      properties:
        oneof:
          type: array
          items:
            $ref: '#/components/schemas/model.StringMatch'
    model.ParamMatch:
      type: object
      properties:
        key:
          type: string
        value:
          $ref: '#/components/schemas/model.StringMatch'
    model.ConditionMatch:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/model.AddressMatch'
        application:
          $ref: '#/components/schemas/model.ListStringMatch'
        param:
          type: array
          items:
            $ref: '#/components/schemas/model.ParamMatch'
        service:
          $ref: '#/components/schemas/model.ListStringMatch'
