openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Traffic Timeout API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: TrafficTimeout
paths:
  /api/{env}/traffic/timeout:
    get:
      description: get timeout rule list
      tags:
      - TrafficTimeout
      summary: Apache Dubbo Get Timeout Rule List
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.Timeout'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvTrafficTimeout
      x-operation-id-source: derived
    put:
      description: update a new timeout rule
      tags:
      - TrafficTimeout
      summary: Apache Dubbo Update a New Timeout Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Timeout'
        description: timeout rule
        required: true
      operationId: putApiByEnvTrafficTimeout
      x-operation-id-source: derived
    post:
      description: Create a new timeout rule
      tags:
      - TrafficTimeout
      summary: Apache Dubbo Create a New Timeout Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Timeout'
        description: timeout rule
        required: true
      operationId: postApiByEnvTrafficTimeout
      x-operation-id-source: derived
    delete:
      description: delete a new timeout rule
      tags:
      - TrafficTimeout
      summary: Apache Dubbo Delete a New Timeout Rule
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: deleteApiByEnvTrafficTimeout
      x-operation-id-source: derived
components:
  schemas:
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
    model.Timeout:
      type: object
      required:
      - service
      - timeout
      properties:
        group:
          type: string
        service:
          type: string
        timeout:
          type: integer
        version:
          type: string
