swagger: '2.0'
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin ConditionRule TrafficGray API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
host: 127.0.0.1:38080
basePath: /
tags:
- name: TrafficGray
paths:
  /api/{env}/traffic/gray:
    get:
      description: get rule list
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficGray
      summary: Apache Dubbo Get Rule List
      parameters:
      - type: string
        description: application name
        name: application
        in: query
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/model.Gray'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    put:
      description: update rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficGray
      summary: Apache Dubbo Update Rule
      parameters:
      - description: rule
        name: gray
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.Gray'
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    post:
      description: create rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficGray
      summary: Apache Dubbo Create Rule
      parameters:
      - description: rule
        name: gray
        in: body
        required: true
        schema:
          $ref: '#/definitions/model.Gray'
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
    delete:
      description: delete rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - TrafficGray
      summary: Apache Dubbo Delete Rule
      parameters:
      - type: string
        description: application name
        name: application
        in: query
        required: true
      responses:
        '200':
          description: OK
          schema:
            type: bool
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
definitions:
  model.StringMatch:
    type: object
    properties:
      empty:
        type: string
      exact:
        type: string
      noempty:
        type: string
      prefix:
        type: string
      regex:
        type: string
      wildcard:
        type: string
  model.Gray:
    type: object
    required:
    - application
    - tags
    properties:
      application:
        type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/model.Tag'
  model.Tag:
    type: object
    required:
    - match
    - name
    properties:
      addresses:
        type: array
        items:
          type: string
      match:
        type: array
        items:
          $ref: '#/definitions/model.ParamMatch'
      name:
        type: string
  model.ParamMatch:
    type: object
    properties:
      key:
        type: string
      value:
        $ref: '#/definitions/model.StringMatch'
  model.HTTPError:
    type: object
    properties:
      error:
        description: error message
        type: string
