openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Traffic Accesslog API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: TrafficAccesslog
paths:
  /api/{env}/traffic/accesslog:
    get:
      description: get rule list
      tags:
      - TrafficAccesslog
      summary: Apache Dubbo Get Rule List
      parameters:
      - description: application name
        name: application
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.Accesslog'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvTrafficAccesslog
      x-operation-id-source: derived
    put:
      description: create rule
      tags:
      - TrafficAccesslog
      summary: Apache Dubbo Create Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Accesslog'
        description: rule
        required: true
      operationId: putApiByEnvTrafficAccesslog
      x-operation-id-source: derived
    post:
      description: create rule
      tags:
      - TrafficAccesslog
      summary: Apache Dubbo Create Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Accesslog'
        description: rule
        required: true
      operationId: postApiByEnvTrafficAccesslog
      x-operation-id-source: derived
    delete:
      description: delete rule
      tags:
      - TrafficAccesslog
      summary: Apache Dubbo Delete Rule
      parameters:
      - description: application name
        name: application
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: deleteApiByEnvTrafficAccesslog
      x-operation-id-source: derived
components:
  schemas:
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
    model.Accesslog:
      type: object
      required:
      - accesslog
      - application
      properties:
        accesslog:
          type: string
        application:
          type: string
