openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Traffic Region API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: TrafficRegion
paths:
  /api/{env}/traffic/region:
    get:
      description: get rule list
      tags:
      - TrafficRegion
      summary: Apache Dubbo Get Rule List
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.Region'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvTrafficRegion
      x-operation-id-source: derived
    put:
      description: update rule
      tags:
      - TrafficRegion
      summary: Apache Dubbo Update Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Region'
        description: rule
        required: true
      operationId: putApiByEnvTrafficRegion
      x-operation-id-source: derived
    post:
      description: create rule
      tags:
      - TrafficRegion
      summary: Apache Dubbo Create Rule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Region'
        description: rule
        required: true
      operationId: postApiByEnvTrafficRegion
      x-operation-id-source: derived
    delete:
      description: delete rule
      tags:
      - TrafficRegion
      summary: Apache Dubbo Delete Rule
      parameters:
      - description: service name
        name: service
        in: query
        required: true
        schema:
          type: string
      - description: service version
        name: version
        in: query
        required: true
        schema:
          type: string
      - description: service group
        name: group
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: bool
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: deleteApiByEnvTrafficRegion
      x-operation-id-source: derived
components:
  schemas:
    model.Region:
      type: object
      required:
      - rule
      - service
      properties:
        group:
          type: string
        rule:
          type: string
        service:
          type: string
        version:
          type: string
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
