openapi: 3.2.0
info:
  description: This is a dubbo-admin swagger ui server.
  title: Dubbo-Admin Mock Rules API
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://127.0.0.1:38080/
tags:
- name: Mock Rules
paths:
  /api/{env}/mock/rule:
    post:
      description: Create or update MockRule
      tags:
      - Mock Rules
      summary: Apache Dubbo Create or Update MockRule
      parameters:
      - description: environment
        name: env
        in: path
        schema:
          type: string
          default: dev
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.MockRule'
        description: MockRule
        required: true
      operationId: postApiByEnvMockRule
      x-operation-id-source: derived
    delete:
      description: Delete MockRule by id
      tags:
      - Mock Rules
      summary: Apache Dubbo Delete MockRule by Id
      parameters:
      - description: environment
        name: env
        in: path
        schema:
          type: string
          default: dev
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.MockRule'
        description: MockRule
        required: true
      operationId: deleteApiByEnvMockRule
      x-operation-id-source: derived
  /api/{env}/mock/rule/list:
    get:
      description: Get MockRules by page
      tags:
      - Mock Rules
      summary: Apache Dubbo Get MockRules by Page
      parameters:
      - description: environment
        name: env
        in: path
        schema:
          type: string
          default: dev
        required: true
      - description: filter condition
        name: filter
        in: query
        schema:
          type: string
      - description: page offset
        name: offset
        in: query
        schema:
          type: integer
      - description: page limit
        name: limit
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.ListMockRulesByPage'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.HTTPError'
      operationId: getApiByEnvMockRuleList
      x-operation-id-source: derived
components:
  schemas:
    model.HTTPError:
      type: object
      properties:
        error:
          description: error message
          type: string
    model.MockRule:
      type: object
      properties:
        enable:
          type: boolean
        id:
          type: integer
        methodName:
          type: string
        rule:
          type: string
        serviceName:
          type: string
    model.ListMockRulesByPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/model.MockRule'
        total:
          type: integer
